package tddcheck

import (
	"fmt"
	"strings"

	"github.com/lwmacct/260622-go-pkg-tddcheck/pkg/markdowntable"
)

func (m ProjectMap) Markdown() string {
	var builder strings.Builder
	builder.WriteString("# tddcheck Project Map\n\n")
	builder.WriteString("<!-- Code generated by tddcheck; DO NOT EDIT. -->\n\n")
	_, _ = fmt.Fprintf(&builder, "- Module: `%s`\n", markdownValue(m.ModulePath))
	_, _ = fmt.Fprintf(&builder, "- Root: `%s`\n", markdownValue(m.Root))

	builder.WriteString("\n## Services\n\n")
	if len(m.Services) == 0 {
		builder.WriteString("No services found.\n")
	} else {
		rows := make([][]string, 0, len(m.Services))
		for _, service := range m.Services {
			rows = append(rows, []string{
				codeCell(service.Name),
				codeCell(service.Scope),
				codeCell(service.File),
				codeCell(service.Constructor),
				serviceMethodNames(service),
			})
		}
		builder.WriteString(markdowntable.Render(markdowntable.Table{
			Header: []string{"Service", "Scope", "File", "Constructor", "Methods"},
			Rows:   rows,
		}))
	}

	builder.WriteString("\n## Tables\n\n")
	if len(m.Tables) == 0 {
		builder.WriteString("No tables found.\n")
	} else {
		for _, table := range m.Tables {
			name := table.Table
			if name == "" {
				name = "(unknown)"
			}
			_, _ = fmt.Fprintf(&builder, "### `%s`\n\n", name)
			_, _ = fmt.Fprintf(&builder, "- Model: `%s`\n", markdownValue(table.Model))
			_, _ = fmt.Fprintf(&builder, "- Scope: `%s`\n", markdownValue(table.Scope))
			_, _ = fmt.Fprintf(&builder, "- File: `%s`\n", markdownValue(table.File))
			if table.Alias != "" {
				_, _ = fmt.Fprintf(&builder, "- Alias: `%s`\n", markdownValue(table.Alias))
			}

			if len(table.Fields) > 0 {
				builder.WriteByte('\n')
				rows := make([][]string, 0, len(table.Fields))
				for _, field := range table.Fields {
					rows = append(rows, []string{
						codeCell(field.Name),
						codeCell(field.Column),
						codeCell(field.GoType),
						fieldOptions(field),
					})
				}
				builder.WriteString(markdowntable.Render(markdowntable.Table{
					Header: []string{"Field", "Column", "Go Type", "Attributes"},
					Rows:   rows,
				}))
			}

			if len(table.ForeignKeys) > 0 {
				builder.WriteString("\nForeign keys:\n\n")
				for _, foreignKey := range table.ForeignKeys {
					_, _ = fmt.Fprintf(&builder, "- `%s`\n", markdownValue(foreignKey))
				}
			}
			builder.WriteString("\n")
		}
	}

	return strings.TrimRight(builder.String(), "\n") + "\n"
}

func serviceMethodNames(service ServiceMap) string {
	if len(service.Methods) == 0 {
		return ""
	}
	names := make([]string, 0, len(service.Methods))
	for _, method := range service.Methods {
		names = append(names, method.Name)
	}
	return strings.Join(names, ", ")
}

func markdownValue(value string) string {
	if value == "" {
		return "-"
	}
	return strings.ReplaceAll(value, "`", "\\`")
}

func codeCell(value string) string {
	return "`" + markdownValue(value) + "`"
}
