package tddcheck

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestProjectRulesMapReportsServicesAndTables(t *testing.T) {
	root := fixture(t, map[string]string{
		"internal/service/identity_user.service.go": `package service
type IdentityUserService struct{}
func NewIdentityUserService() *IdentityUserService { return &IdentityUserService{} }
func (s *IdentityUserService) Create() {}
func (s *IdentityUserService) Search() {}
`,
		"internal/service/o_auth_flow.service.go": `package service
type OAuthFlowService struct{}
func NewOAuthFlowService() *OAuthFlowService { return &OAuthFlowService{} }
func (s *OAuthFlowService) Consume() {}
`,
		"internal/repository/identity_user.schema.go": `package repository
import (
	"context"
	"time"
	"github.com/uptrace/bun"
)
type IdentityUserModel struct {
	bun.BaseModel ` + "`" + `bun:"table:users,alias:u"` + "`" + `
	ID int64 ` + "`" + `bun:"id,pk,autoincrement"` + "`" + `
	Username string ` + "`" + `bun:"username,notnull,unique"` + "`" + `
	Email string ` + "`" + `bun:"email,nullzero"` + "`" + `
	CreatedAt time.Time ` + "`" + `bun:"created_at,notnull"` + "`" + `
}
func (*IdentityUserModel) BeforeCreateTable(_ context.Context, query *bun.CreateTableQuery) error {
	query.ForeignKey("(id) REFERENCES accounts (user_id) ON DELETE CASCADE")
	return nil
}
func IdentityUserSchema() {}
`,
		"internal/repository/auth_identity.schema.go": `package repository
import "github.com/uptrace/bun"
type AuthIdentityModel struct {
	bun.BaseModel ` + "`" + `bun:"table:auth_identities,alias:ai"` + "`" + `
	ID int64 ` + "`" + `bun:"id,pk,autoincrement"` + "`" + `
	Provider string ` + "`" + `bun:"provider,notnull,unique:provider_subject"` + "`" + `
	Subject string ` + "`" + `bun:"subject,notnull,unique:provider_subject"` + "`" + `
}
func AuthIdentitySchema() {}
`,
	})

	projectMap, err := (ProjectRules{Root: filepath.Join(root, "internal")}).Map()
	if err != nil {
		t.Fatal(err)
	}

	if projectMap.ModulePath != "example.com/app" {
		t.Fatalf("unexpected module path %q", projectMap.ModulePath)
	}
	assertServiceMap(t, projectMap, "IdentityUserService", "identity_user", "NewIdentityUserService", []string{"Create", "Search"})
	assertServiceMap(t, projectMap, "OAuthFlowService", "o_auth_flow", "NewOAuthFlowService", []string{"Consume"})

	users := findTableMap(projectMap, "users")
	if users == nil {
		t.Fatalf("expected users table, got %#v", projectMap.Tables)
	}
	if users.Model != "IdentityUserModel" || users.Alias != "u" || users.Scope != "identity_user" {
		t.Fatalf("unexpected users table metadata: %#v", users)
	}
	assertFieldMap(t, *users, "ID", "id", "int64", true, true, false, false, "")
	assertFieldMap(t, *users, "Username", "username", "string", false, false, true, false, "true")
	assertFieldMap(t, *users, "Email", "email", "string", false, false, false, true, "")
	if len(users.ForeignKeys) != 1 || users.ForeignKeys[0] != "(id) REFERENCES accounts (user_id) ON DELETE CASCADE" {
		t.Fatalf("unexpected foreign keys: %#v", users.ForeignKeys)
	}

	authIdentities := findTableMap(projectMap, "auth_identities")
	if authIdentities == nil {
		t.Fatalf("expected auth_identities table, got %#v", projectMap.Tables)
	}
	assertFieldMap(t, *authIdentities, "Provider", "provider", "string", false, false, true, false, "provider_subject")
	assertFieldMap(t, *authIdentities, "Subject", "subject", "string", false, false, true, false, "provider_subject")
}

func TestProjectMapTextIncludesServicesAndTables(t *testing.T) {
	projectMap := ProjectMap{
		Root:       "internal",
		ModulePath: "example.com/app",
		Services: []ServiceMap{{
			Scope:       "device",
			Name:        "DeviceService",
			Constructor: "NewDeviceService",
			File:        "internal/service/device.service.go",
			Methods:     []MethodMap{{Name: "List"}},
		}},
		Tables: []TableMap{{
			Scope: "device",
			Model: "DeviceModel",
			Table: "devices",
			Alias: "d",
			File:  "internal/repository/device.schema.go",
			Fields: []FieldMap{{
				Name:       "ID",
				Column:     "id",
				GoType:     "int64",
				PrimaryKey: true,
			}},
		}},
	}

	text := projectMap.Text()
	for _, needle := range []string{
		"tddcheck map: example.com/app",
		"- DeviceService (device) internal/service/device.service.go",
		"constructor: NewDeviceService",
		"methods: List",
		"- devices (DeviceModel, device) internal/repository/device.schema.go",
		"alias: d",
		"ID int64 `id` [pk]",
	} {
		if !strings.Contains(text, needle) {
			t.Fatalf("expected text to contain %q, got:\n%s", needle, text)
		}
	}
}

func TestProjectMapMarkdownIncludesServicesAndTables(t *testing.T) {
	projectMap := projectMapFixture()

	markdown := projectMap.Markdown()
	for _, needle := range []string{
		"# tddcheck Project Map",
		"<!-- Code generated by tddcheck; DO NOT EDIT. -->",
		"- Module: `example.com/app`",
		"| `DeviceService` | `device` | `internal/service/device.service.go` | `NewDeviceService` | List |",
		"### `devices`",
		"- Model: `DeviceModel`",
		"| `ID` | `id` | `int64` | [pk] |",
	} {
		if !strings.Contains(markdown, needle) {
			t.Fatalf("expected markdown to contain %q, got:\n%s", needle, markdown)
		}
	}
}

func TestProjectMapDocWriteWritesDefaultMarkdownFile(t *testing.T) {
	root := fixture(t, map[string]string{
		"internal/service/device.service.go": `package service
type DeviceService struct{}
func NewDeviceService() *DeviceService { return &DeviceService{} }
func (s *DeviceService) List() {}
`,
		"internal/repository/device.schema.go": `package repository
import "github.com/uptrace/bun"
type DeviceModel struct {
	bun.BaseModel ` + "`" + `bun:"table:devices,alias:d"` + "`" + `
	ID int64 ` + "`" + `bun:"id,pk"` + "`" + `
}
func DeviceSchema() {}
`,
	})
	cwd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		_ = os.Chdir(cwd)
	})
	if err := os.Chdir(root); err != nil {
		t.Fatal(err)
	}

	ProjectMapDoc{Root: "internal"}.Write(t)

	data, err := os.ReadFile(filepath.Join(root, DefaultProjectMapDocFile))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), "### `devices`") {
		t.Fatalf("expected generated doc to contain devices table, got:\n%s", string(data))
	}
}

func projectMapFixture() ProjectMap {
	return ProjectMap{
		Root:       "internal",
		ModulePath: "example.com/app",
		Services: []ServiceMap{{
			Scope:       "device",
			Name:        "DeviceService",
			Constructor: "NewDeviceService",
			File:        "internal/service/device.service.go",
			Methods:     []MethodMap{{Name: "List"}},
		}},
		Tables: []TableMap{{
			Scope: "device",
			Model: "DeviceModel",
			Table: "devices",
			Alias: "d",
			File:  "internal/repository/device.schema.go",
			Fields: []FieldMap{{
				Name:       "ID",
				Column:     "id",
				GoType:     "int64",
				PrimaryKey: true,
			}},
		}},
	}
}

func assertServiceMap(t *testing.T, projectMap ProjectMap, name string, scope string, constructor string, methods []string) {
	t.Helper()

	for _, service := range projectMap.Services {
		if service.Name != name {
			continue
		}
		if service.Scope != scope || service.Constructor != constructor {
			t.Fatalf("unexpected service metadata for %s: %#v", name, service)
		}
		for _, method := range methods {
			found := false
			for _, item := range service.Methods {
				if item.Name == method {
					found = true
					break
				}
			}
			if !found {
				t.Fatalf("expected service %s to include method %s, got %#v", name, method, service.Methods)
			}
		}
		return
	}
	t.Fatalf("expected service %s, got %#v", name, projectMap.Services)
}

func findTableMap(projectMap ProjectMap, table string) *TableMap {
	for index := range projectMap.Tables {
		if projectMap.Tables[index].Table == table {
			return &projectMap.Tables[index]
		}
	}
	return nil
}

func assertFieldMap(t *testing.T, table TableMap, name string, column string, goType string, primaryKey bool, autoIncrement bool, notNull bool, nullable bool, unique string) {
	t.Helper()

	for _, field := range table.Fields {
		if field.Name != name {
			continue
		}
		if field.Column != column ||
			field.GoType != goType ||
			field.PrimaryKey != primaryKey ||
			field.AutoIncrement != autoIncrement ||
			field.NotNull != notNull ||
			field.Nullable != nullable ||
			field.Unique != unique {
			t.Fatalf("unexpected field metadata for %s.%s: %#v", table.Table, name, field)
		}
		return
	}
	t.Fatalf("expected field %s in table %s, got %#v", name, table.Table, table.Fields)
}
