package tddcheck

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestProjectAnalyzeReportsIndex(t *testing.T) {
	root := fixture(t, map[string]string{
		"internal/handler/identity_user.handler.go": `package handler
import (
	"net/http"
	"github.com/danielgtaylor/huma/v2"
)
type identityUserHandler struct{}
func RegisterIdentityUsers(api huma.API) {
	users := huma.NewGroup(api, "/identity/users")
	huma.Register(users, huma.Operation{OperationID: "identity-user-list", Method: http.MethodGet, Path: "", Tags: []string{"Identity"}}, identityUserHandler{}.List)
}
func (h identityUserHandler) List() {}
`,
		"internal/service/identity_user.service.go": `package service
type AuthSessionService struct{}
func NewAuthSessionService() *AuthSessionService { return &AuthSessionService{} }
type IdentityUserService struct { sessions *AuthSessionService }
func NewIdentityUserService() *IdentityUserService { return &IdentityUserService{} }
func (s *IdentityUserService) Create() {}
func (s *IdentityUserService) Search() {}
`,
		"internal/repository/identity_user.store.go": `package repository
import "context"
func (s *Store) FetchIdentityUser(ctx context.Context, id int64) (string, error) { return "", nil }
func (s *Store) ListIdentityUsers(ctx context.Context) ([]string, error) { return nil, nil }
`,
		"internal/repository/identity_user.schema.go": `package repository
import (
	"context"
	"time"
	"github.com/uptrace/bun"
)
type IdentityUserModel struct {
	bun.BaseModel ` + "`" + `bun:"table:users,alias:u"` + "`" + `
	ID int64 ` + "`" + `bun:"id,pk,autoincrement"` + "`" + `
	Username string ` + "`" + `bun:"username,notnull,unique"` + "`" + `
	Email string ` + "`" + `bun:"email,nullzero"` + "`" + `
	CreatedAt time.Time ` + "`" + `bun:"created_at,notnull"` + "`" + `
}
func (*IdentityUserModel) BeforeCreateTable(_ context.Context, query *bun.CreateTableQuery) error {
	query.ForeignKey("(id) REFERENCES accounts (user_id) ON DELETE CASCADE")
	return nil
}
func IdentityUserSchema() {}
`,
	})

	analysis, err := (Project{Root: filepath.Join(root, "internal")}).Analyze()
	if err != nil {
		t.Fatal(err)
	}
	index := analysis.ProjectIndex()

	if index.ModulePath != "example.com/app" {
		t.Fatalf("unexpected module path %q", index.ModulePath)
	}
	assertAPIIndex(t, index, "GET", "/identity/users", "identity-user-list", "List", []string{"Identity"})
	assertHandlerIndex(t, index, "identity_user", "identityUserHandler", "RegisterIdentityUsers", []string{"List"})
	assertServiceIndex(t, index, "IdentityUserService", "identity_user", "NewIdentityUserService", []string{"AuthSessionService"}, []string{"Create", "Search"})
	assertStoreIndex(t, index, "identity_user", []string{"FetchIdentityUser", "ListIdentityUsers"})

	users := findTableIndex(index, "users")
	if users == nil {
		t.Fatalf("expected users table, got %#v", index.Tables)
	}
	if users.Model != "IdentityUserModel" || users.Alias != "u" || users.Scope != "identity_user" {
		t.Fatalf("unexpected users table metadata: %#v", users)
	}
	assertFieldIndex(t, *users, "ID", "id", "int64", true, true, false, false, "")
	assertFieldIndex(t, *users, "Username", "username", "string", false, false, true, false, "true")
	assertFieldIndex(t, *users, "Email", "email", "string", false, false, false, true, "")
	if len(users.ForeignKeys) != 1 || users.ForeignKeys[0] != "(id) REFERENCES accounts (user_id) ON DELETE CASCADE" {
		t.Fatalf("unexpected foreign keys: %#v", users.ForeignKeys)
	}
}

func TestIndexTextIncludesSections(t *testing.T) {
	index := indexFixture()

	text := index.Text()
	for _, needle := range []string{
		"tddcheck index: example.com/app",
		"apis:",
		"- GET /devices (device) internal/handler/device.handler.go",
		"operation: list-devices",
		"handlers:",
		"- deviceHandler (device) internal/handler/device.handler.go",
		"services:",
		"- DeviceService (device) internal/service/device.service.go",
		"dependencies: AuthSessionService",
		"stores:",
		"- device internal/repository/device.store.go",
		"tables:",
		"- devices (DeviceModel, device) internal/repository/device.schema.go",
		"ID int64 `id` [pk]",
	} {
		if !strings.Contains(text, needle) {
			t.Fatalf("expected text to contain %q, got:\n%s", needle, text)
		}
	}
}

func TestAnalysisMarkdownIncludesIndex(t *testing.T) {
	analysis := Analysis{
		Root:       "internal",
		ModulePath: "example.com/app",
		Index:      indexFixture(),
	}

	markdown := analysis.Markdown()
	for _, needle := range []string{
		"# tddcheck Architecture Index",
		"<!-- Code generated by tddcheck; DO NOT EDIT. -->",
		"- Module: `example.com/app`",
		"- Violations: `0`",
		"## APIs",
		"| Method | Full Path",
		"| `GET`  | `/devices`",
		"| `GET`  | `/devices` | `-`",
		"## Handlers",
		"| `device` | `deviceHandler` | `RegisterDevices` | `internal/handler/device.handler.go` | List    |",
		"## Services",
		"| `DeviceService` | `device` | `internal/service/device.service.go` | `NewDeviceService` | AuthSessionService | List    |",
		"## Stores",
		"| `device` | `internal/repository/device.store.go` | FetchDevice |",
		"## Tables",
		"| `devices` | `DeviceModel` | `device` | `internal/repository/device.schema.go` | `d`   | 1      | 0            |",
		"### `devices`",
		"| `ID`  | `id`   | `int64` | [pk]       |",
	} {
		if !strings.Contains(markdown, needle) {
			t.Fatalf("expected markdown to contain %q, got:\n%s", needle, markdown)
		}
	}
}

func TestProjectWriteDocWritesDefaultMarkdownFile(t *testing.T) {
	root := fixture(t, map[string]string{
		"internal/service/device.service.go": `package service
type DeviceService struct{}
func NewDeviceService() *DeviceService { return &DeviceService{} }
func (s *DeviceService) List() {}
`,
		"internal/repository/device.schema.go": `package repository
import "github.com/uptrace/bun"
type DeviceModel struct {
	bun.BaseModel ` + "`" + `bun:"table:devices,alias:d"` + "`" + `
	ID int64 ` + "`" + `bun:"id,pk"` + "`" + `
}
func DeviceSchema() {}
`,
	})
	cwd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		_ = os.Chdir(cwd)
	})
	if err := os.Chdir(root); err != nil {
		t.Fatal(err)
	}

	Project{Root: "internal"}.WriteDoc(t, "")

	data, err := os.ReadFile(filepath.Join(root, DefaultDocFile))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), "### `devices`") {
		t.Fatalf("expected generated doc to contain devices table, got:\n%s", string(data))
	}
}

func TestProjectAnalyzeIndexesMultipleHandlerRegisters(t *testing.T) {
	root := fixture(t, map[string]string{
		"internal/handler/device.handler.go": `package handler
import "github.com/danielgtaylor/huma/v2"
type deviceHandler struct{}
func RegisterDevices(api huma.API) { deviceHandler{}.registerAdmin(api) }
func RegisterPublicDevices(api huma.API) { deviceHandler{}.registerPublic(api) }
func (h deviceHandler) registerAdmin(api huma.API) {}
func (h deviceHandler) registerPublic(api huma.API) {}
`,
	})

	analysis, err := (Project{Root: filepath.Join(root, "internal")}).Analyze()
	if err != nil {
		t.Fatal(err)
	}
	assertHandlerIndex(t, analysis.ProjectIndex(), "device", "deviceHandler", "RegisterDevices", []string{"registerAdmin", "registerPublic"})
	assertHandlerIndex(t, analysis.ProjectIndex(), "device", "deviceHandler", "RegisterPublicDevices", []string{"registerAdmin", "registerPublic"})
}

func TestProjectAnalyzeAssignsForeignKeysToReceiverModel(t *testing.T) {
	root := fixture(t, map[string]string{
		"internal/repository/device.schema.go": `package repository
import (
	"context"
	"github.com/uptrace/bun"
)
type DeviceModel struct {
	bun.BaseModel ` + "`" + `bun:"table:devices"` + "`" + `
	ID int64 ` + "`" + `bun:"id,pk"` + "`" + `
}
func (*DeviceModel) BeforeCreateTable(_ context.Context, query *bun.CreateTableQuery) error {
	query.ForeignKey("(room_id) REFERENCES rooms (id)")
	return nil
}
type DevicePortModel struct {
	bun.BaseModel ` + "`" + `bun:"table:device_ports"` + "`" + `
	ID int64 ` + "`" + `bun:"id,pk"` + "`" + `
}
func (*DevicePortModel) BeforeCreateTable(_ context.Context, query *bun.CreateTableQuery) error {
	query.ForeignKey("(device_id) REFERENCES devices (id)")
	return nil
}
type DeviceRowModel struct {
	DeviceModel ` + "`" + `bun:",extend"` + "`" + `
	RoomName string ` + "`" + `bun:"room_name"` + "`" + `
}
`,
	})

	analysis, err := (Project{Root: filepath.Join(root, "internal")}).Analyze()
	if err != nil {
		t.Fatal(err)
	}
	index := analysis.ProjectIndex()
	devices := findTableIndex(index, "devices")
	if devices == nil || len(devices.ForeignKeys) != 1 || devices.ForeignKeys[0] != "(room_id) REFERENCES rooms (id)" {
		t.Fatalf("unexpected devices table: %#v", devices)
	}
	ports := findTableIndex(index, "device_ports")
	if ports == nil || len(ports.ForeignKeys) != 1 || ports.ForeignKeys[0] != "(device_id) REFERENCES devices (id)" {
		t.Fatalf("unexpected ports table: %#v", ports)
	}
	if len(index.Projections) != 1 || index.Projections[0].Model != "DeviceRowModel" || index.Projections[0].Extends[0] != "DeviceModel" {
		t.Fatalf("expected DeviceRowModel projection, got %#v", index.Projections)
	}
}

func TestProjectAnalyzeAppliesChiHumachiMountPaths(t *testing.T) {
	root := fixture(t, map[string]string{
		"internal/handler/x_http.endpoint.go": `package handler
import (
	"net/http"
	"github.com/danielgtaylor/huma/v2"
	"github.com/danielgtaylor/huma/v2/adapters/humachi"
	"github.com/go-chi/chi/v5"
)
type Endpoint struct{}
func utilHTTPConfig(title string, basePath string) huma.Config { return huma.DefaultConfig(title, "1.0.0") }
func (e *Endpoint) Handler() http.Handler {
	router := chi.NewRouter()
	RegisterRootSystem(humachi.New(router, utilHTTPConfig("Root", "")))
	router.Route("/api/public", func(publicRouter chi.Router) {
		publicAPI := humachi.New(publicRouter, utilHTTPConfig("Public", "/api/public"))
		e.RegisterPublic(publicAPI)
	})
	router.Route("/api", func(adminRouter chi.Router) {
		adminAPI := humachi.New(adminRouter, utilHTTPConfig("Admin", "/api"))
		e.RegisterAdmin(adminAPI)
	})
	return router
}
func (e *Endpoint) RegisterAdmin(api huma.API) { RegisterDevices(api) }
func (e *Endpoint) RegisterPublic(api huma.API) { RegisterPublicDevices(api) }
`,
		"internal/handler/system.handler.go": `package handler
import (
	"net/http"
	"github.com/danielgtaylor/huma/v2"
)
type systemHandler struct{}
func RegisterRootSystem(api huma.API) {
	huma.Register(api, huma.Operation{OperationID: "health", Method: http.MethodGet, Path: "/health"}, systemHandler{}.health)
}
func (h systemHandler) health() {}
`,
		"internal/handler/device.handler.go": `package handler
import (
	"net/http"
	"github.com/danielgtaylor/huma/v2"
)
type deviceHandler struct{}
func RegisterDevices(api huma.API) { deviceHandler{}.registerAdmin(api) }
func RegisterPublicDevices(api huma.API) { deviceHandler{}.registerPublic(api) }
func (h deviceHandler) registerAdmin(api huma.API) {
	huma.Register(api, huma.Operation{OperationID: "list-devices", Method: http.MethodGet, Path: "/devices"}, h.list)
}
func (h deviceHandler) registerPublic(api huma.API) {
	huma.Register(api, huma.Operation{OperationID: "public-devices", Method: http.MethodGet, Path: "/devices"}, h.publicList)
}
func (h deviceHandler) list() {}
func (h deviceHandler) publicList() {}
`,
	})

	analysis, err := (Project{Root: filepath.Join(root, "internal")}).Analyze()
	if err != nil {
		t.Fatal(err)
	}
	index := analysis.ProjectIndex()
	assertAPIIndex(t, index, "GET", "/health", "health", "health", nil)
	admin := findAPIIndex(index, "list-devices")
	if admin == nil || admin.MountPath != "/api" || admin.OperationPath != "/devices" || admin.FullPath != "/api/devices" {
		t.Fatalf("unexpected admin api: %#v", admin)
	}
	public := findAPIIndex(index, "public-devices")
	if public == nil || public.MountPath != "/api/public" || public.OperationPath != "/devices" || public.FullPath != "/api/public/devices" {
		t.Fatalf("unexpected public api: %#v", public)
	}
}

func indexFixture() Index {
	return Index{
		Root:       "internal",
		ModulePath: "example.com/app",
		APIs: []APIIndex{{
			Scope:         "device",
			Method:        "GET",
			OperationPath: "/devices",
			FullPath:      "/devices",
			OperationID:   "list-devices",
			Tags:          []string{"Device"},
			Handler:       "List",
			Register:      "RegisterDevices",
			File:          "internal/handler/device.handler.go",
		}},
		Handlers: []HandlerIndex{{
			Scope:     "device",
			Type:      "deviceHandler",
			Registers: []string{"RegisterDevices"},
			File:      "internal/handler/device.handler.go",
			Methods:   []MethodIndex{{Name: "List"}},
		}},
		Services: []ServiceIndex{{
			Scope:        "device",
			Type:         "DeviceService",
			Constructor:  "NewDeviceService",
			File:         "internal/service/device.service.go",
			Methods:      []MethodIndex{{Name: "List"}},
			Dependencies: []string{"AuthSessionService"},
		}},
		Stores: []StoreIndex{{
			Scope:   "device",
			File:    "internal/repository/device.store.go",
			Methods: []MethodIndex{{Name: "FetchDevice"}},
		}},
		Tables: []TableIndex{{
			Scope: "device",
			Model: "DeviceModel",
			Table: "devices",
			Alias: "d",
			File:  "internal/repository/device.schema.go",
			Fields: []FieldIndex{{
				Name:       "ID",
				Column:     "id",
				GoType:     "int64",
				PrimaryKey: true,
			}},
		}},
	}
}

func assertAPIIndex(t *testing.T, index Index, method string, path string, operationID string, handler string, tags []string) {
	t.Helper()

	for _, api := range index.APIs {
		if api.Method != method || api.FullPath != path || api.OperationID != operationID {
			continue
		}
		if api.Handler != handler {
			t.Fatalf("unexpected api handler for %s %s: %#v", method, path, api)
		}
		for _, tag := range tags {
			if !stringIn(tag, api.Tags) {
				t.Fatalf("expected tag %s in %#v", tag, api.Tags)
			}
		}
		return
	}
	t.Fatalf("expected api %s %s %s, got %#v", method, path, operationID, index.APIs)
}

func assertHandlerIndex(t *testing.T, index Index, scope string, handlerType string, register string, methods []string) {
	t.Helper()

	for _, handler := range index.Handlers {
		if handler.Scope != scope {
			continue
		}
		if handler.Type != handlerType || !stringIn(register, handler.Registers) {
			t.Fatalf("unexpected handler metadata for %s: %#v", scope, handler)
		}
		assertMethods(t, handler.Methods, methods)
		return
	}
	t.Fatalf("expected handler %s, got %#v", scope, index.Handlers)
}

func assertServiceIndex(t *testing.T, index Index, serviceType string, scope string, constructor string, dependencies []string, methods []string) {
	t.Helper()

	for _, service := range index.Services {
		if service.Type != serviceType {
			continue
		}
		if service.Scope != scope || service.Constructor != constructor {
			t.Fatalf("unexpected service metadata for %s: %#v", serviceType, service)
		}
		for _, dependency := range dependencies {
			if !stringIn(dependency, service.Dependencies) {
				t.Fatalf("expected dependency %s in %#v", dependency, service.Dependencies)
			}
		}
		assertMethods(t, service.Methods, methods)
		return
	}
	t.Fatalf("expected service %s, got %#v", serviceType, index.Services)
}

func assertStoreIndex(t *testing.T, index Index, scope string, methods []string) {
	t.Helper()

	for _, store := range index.Stores {
		if store.Scope != scope {
			continue
		}
		assertMethods(t, store.Methods, methods)
		return
	}
	t.Fatalf("expected store %s, got %#v", scope, index.Stores)
}

func assertMethods(t *testing.T, values []MethodIndex, methods []string) {
	t.Helper()

	for _, method := range methods {
		found := false
		for _, item := range values {
			if item.Name == method {
				found = true
				break
			}
		}
		if !found {
			t.Fatalf("expected method %s, got %#v", method, values)
		}
	}
}

func findTableIndex(index Index, table string) *TableIndex {
	for itemIndex := range index.Tables {
		if index.Tables[itemIndex].Table == table {
			return &index.Tables[itemIndex]
		}
	}
	return nil
}

func findAPIIndex(index Index, operationID string) *APIIndex {
	for itemIndex := range index.APIs {
		if index.APIs[itemIndex].OperationID == operationID {
			return &index.APIs[itemIndex]
		}
	}
	return nil
}

func assertFieldIndex(t *testing.T, table TableIndex, name string, column string, goType string, primaryKey bool, autoIncrement bool, notNull bool, nullable bool, unique string) {
	t.Helper()

	for _, field := range table.Fields {
		if field.Name != name {
			continue
		}
		if field.Column != column ||
			field.GoType != goType ||
			field.PrimaryKey != primaryKey ||
			field.AutoIncrement != autoIncrement ||
			field.NotNull != notNull ||
			field.Nullable != nullable ||
			field.Unique != unique {
			t.Fatalf("unexpected field metadata for %s.%s: %#v", table.Table, name, field)
		}
		return
	}
	t.Fatalf("expected field %s in table %s, got %#v", name, table.Table, table.Fields)
}

func stringIn(value string, values []string) bool {
	for _, item := range values {
		if item == value {
			return true
		}
	}
	return false
}
