package tddcheck

import (
	"fmt"
	"strings"

	"github.com/lwmacct/260622-go-pkg-tddcheck/pkg/markdowntable"
)

// Markdown renders the analysis as a generated Markdown architecture index.
func (a Analysis) Markdown() string {
	return a.ArchitectureIndex().Markdown(a)
}

// Markdown renders the index as Markdown using analysis for result metadata.
func (i Index) Markdown(analysis Analysis) string {
	var builder strings.Builder
	builder.WriteString("# tddcheck Architecture Index\n\n")
	builder.WriteString("<!-- Code generated by tddcheck; DO NOT EDIT. -->\n\n")
	_, _ = fmt.Fprintf(&builder, "- Schema: `%s`\n", markdownValue(analysis.SchemaVersion))
	_, _ = fmt.Fprintf(&builder, "- Module: `%s`\n", markdownValue(i.ModulePath))
	_, _ = fmt.Fprintf(&builder, "- Root: `%s`\n", markdownValue(i.Root))
	_, _ = fmt.Fprintf(&builder, "- Violations: `%d`\n", len(analysis.Diagnostics))

	builder.WriteString("\n## Unclassified Files\n\n")
	if len(analysis.UnclassifiedFiles) == 0 {
		builder.WriteString("No unclassified files found.\n")
	} else {
		for _, file := range analysis.UnclassifiedFiles {
			_, _ = fmt.Fprintf(&builder, "- `%s`\n", markdownValue(file))
		}
	}

	builder.WriteString("\n## Free Files\n\n")
	if len(analysis.FreeFiles) == 0 {
		builder.WriteString("No free files found.\n")
	} else {
		rows := make([][]string, 0, len(analysis.FreeFiles))
		for _, freeFile := range analysis.FreeFiles {
			rows = append(rows, []string{
				codeCell(freeFile.Identity.Layer),
				codeCell(freeFile.Identity.Subject),
				codeCell(freeFile.Identity.Namespace),
				codeCell(freeFile.File),
			})
		}
		builder.WriteString(markdowntable.Render(markdowntable.Table{
			Header: []string{"Layer", "Subject", "Namespace", "File"},
			Rows:   rows,
		}))
	}

	builder.WriteString("\n## Handlers\n\n")
	if len(i.Handlers) == 0 {
		builder.WriteString("No handlers found.\n")
	} else {
		rows := make([][]string, 0, len(i.Handlers))
		for _, handler := range i.Handlers {
			rows = append(rows, append(identityCells(handler.Identity),
				codeCell(handler.Type),
				codeCell(strings.Join(handler.Registers, ", ")),
				codeCell(handler.File),
				methodNames(handler.Methods),
			))
		}
		builder.WriteString(markdowntable.Render(markdowntable.Table{
			Header: []string{"Subject", "Namespace", "Kind", "Handler", "Register", "File", "Methods"},
			Rows:   rows,
		}))
	}

	builder.WriteString("\n## Services\n\n")
	if len(i.Services) == 0 {
		builder.WriteString("No services found.\n")
	} else {
		rows := make([][]string, 0, len(i.Services))
		for _, service := range i.Services {
			rows = append(rows, append([]string{codeCell(service.Type)}, append(identityCells(service.Identity),
				codeCell(service.File),
				codeCell(service.Constructor),
				strings.Join(service.Dependencies, ", "),
				methodNames(service.Methods),
			)...))
		}
		builder.WriteString(markdowntable.Render(markdowntable.Table{
			Header: []string{"Service", "Subject", "Namespace", "Kind", "File", "Constructor", "Dependencies", "Methods"},
			Rows:   rows,
		}))
	}

	builder.WriteString("\n## Stores\n\n")
	if len(i.Stores) == 0 {
		builder.WriteString("No stores found.\n")
	} else {
		rows := make([][]string, 0, len(i.Stores))
		for _, store := range i.Stores {
			rows = append(rows, append(identityCells(store.Identity),
				codeCell(store.File),
				methodNames(store.Methods),
			))
		}
		builder.WriteString(markdowntable.Render(markdowntable.Table{
			Header: []string{"Subject", "Namespace", "Kind", "File", "Methods"},
			Rows:   rows,
		}))
	}

	builder.WriteString("\n## Tables\n\n")
	if len(i.Tables) == 0 {
		builder.WriteString("No tables found.\n")
	} else {
		builder.WriteString(markdowntable.Render(markdowntable.Table{
			Header: []string{"Table", "Model", "Subject", "Namespace", "Kind", "File", "Alias", "Fields", "Foreign Keys"},
			Rows:   tableSummaryRows(i.Tables),
		}))
		builder.WriteString("\n")
		for _, table := range i.Tables {
			name := table.Table
			if name == "" {
				name = "(unknown)"
			}
			_, _ = fmt.Fprintf(&builder, "### `%s`\n\n", name)
			_, _ = fmt.Fprintf(&builder, "- Model: `%s`\n", markdownValue(table.Model))
			writeIdentityMarkdown(&builder, table.Identity)
			_, _ = fmt.Fprintf(&builder, "- File: `%s`\n", markdownValue(table.File))
			if table.Alias != "" {
				_, _ = fmt.Fprintf(&builder, "- Alias: `%s`\n", markdownValue(table.Alias))
			}

			if len(table.Fields) > 0 {
				builder.WriteByte('\n')
				rows := make([][]string, 0, len(table.Fields))
				for _, field := range table.Fields {
					rows = append(rows, []string{
						codeCell(field.Name),
						codeCell(field.Column),
						codeCell(field.GoType),
						fieldOptions(field),
					})
				}
				builder.WriteString(markdowntable.Render(markdowntable.Table{
					Header: []string{"Field", "Column", "Go Type", "Attributes"},
					Rows:   rows,
				}))
			}

			if len(table.ForeignKeys) > 0 {
				builder.WriteString("\nForeign keys:\n\n")
				for _, foreignKey := range table.ForeignKeys {
					_, _ = fmt.Fprintf(&builder, "- `%s`\n", markdownValue(foreignKey))
				}
			}
			builder.WriteString("\n")
		}
	}

	builder.WriteString("\n## Projections\n\n")
	if len(i.Projections) == 0 {
		builder.WriteString("No projections found.\n")
	} else {
		builder.WriteString(markdowntable.Render(markdowntable.Table{
			Header: []string{"Model", "Subject", "Namespace", "Kind", "File", "Extends", "Fields"},
			Rows:   projectionSummaryRows(i.Projections),
		}))
		builder.WriteString("\n")
		for _, projection := range i.Projections {
			_, _ = fmt.Fprintf(&builder, "### `%s`\n\n", markdownValue(projection.Model))
			writeIdentityMarkdown(&builder, projection.Identity)
			_, _ = fmt.Fprintf(&builder, "- File: `%s`\n", markdownValue(projection.File))
			if len(projection.Extends) > 0 {
				_, _ = fmt.Fprintf(&builder, "- Extends: `%s`\n", markdownValue(strings.Join(projection.Extends, ", ")))
			}
			if len(projection.Fields) > 0 {
				builder.WriteByte('\n')
				rows := make([][]string, 0, len(projection.Fields))
				for _, field := range projection.Fields {
					rows = append(rows, []string{
						codeCell(field.Name),
						codeCell(field.Column),
						codeCell(field.GoType),
						fieldOptions(field),
					})
				}
				builder.WriteString(markdowntable.Render(markdowntable.Table{
					Header: []string{"Field", "Column", "Go Type", "Attributes"},
					Rows:   rows,
				}))
			}
			builder.WriteString("\n")
		}
	}

	return strings.TrimRight(builder.String(), "\n") + "\n"
}

func tableSummaryRows(tables []TableIndex) [][]string {
	rows := make([][]string, 0, len(tables))
	for _, table := range tables {
		name := table.Table
		if name == "" {
			name = "(unknown)"
		}
		rows = append(rows, append([]string{
			codeCell(name),
			codeCell(table.Model),
		}, append(identityCells(table.Identity),
			codeCell(table.File),
			codeCell(table.Alias),
			fmt.Sprint(len(table.Fields)),
			fmt.Sprint(len(table.ForeignKeys)),
		)...))
	}
	return rows
}

func projectionSummaryRows(projections []ProjectionIndex) [][]string {
	rows := make([][]string, 0, len(projections))
	for _, projection := range projections {
		rows = append(rows, append([]string{
			codeCell(projection.Model),
		}, append(identityCells(projection.Identity),
			codeCell(projection.File),
			strings.Join(projection.Extends, ", "),
			fmt.Sprint(len(projection.Fields)),
		)...))
	}
	return rows
}

func methodNames(methods []MethodIndex) string {
	if len(methods) == 0 {
		return ""
	}
	names := make([]string, 0, len(methods))
	for _, method := range methods {
		names = append(names, method.Name)
	}
	return strings.Join(names, ", ")
}

func markdownValue(value string) string {
	if value == "" {
		return "-"
	}
	return strings.ReplaceAll(value, "`", "\\`")
}

func codeCell(value string) string {
	return "`" + markdownValue(value) + "`"
}

func identityCells(identity FileIdentity) []string {
	return []string{
		codeCell(identity.Subject),
		codeCell(identity.Namespace),
		codeCell(identity.Kind),
	}
}

func writeIdentityMarkdown(builder *strings.Builder, identity FileIdentity) {
	_, _ = fmt.Fprintf(builder, "- Subject: `%s`\n", markdownValue(identity.Subject))
	_, _ = fmt.Fprintf(builder, "- Namespace: `%s`\n", markdownValue(identity.Namespace))
	_, _ = fmt.Fprintf(builder, "- Kind: `%s`\n", markdownValue(identity.Kind))
}
