package tddcheck

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestProjectAnalyzeReportsIndex(t *testing.T) {
	root := fixture(t, map[string]string{
		"internal/handler/identity_user.handler.go": `package handler
type identityUserHandler struct{}
func RegisterIdentityUsers() {}
func (h identityUserHandler) List() {}
`,
		"internal/service/identity_user.service.go": `package service
type AuthSessionService struct{}
func NewAuthSessionService() *AuthSessionService { return &AuthSessionService{} }
type IdentityUserService struct { sessions *AuthSessionService }
func NewIdentityUserService() *IdentityUserService { return &IdentityUserService{} }
func (s *IdentityUserService) Create() {}
func (s *IdentityUserService) Search() {}
`,
		"internal/repository/identity_user.store.go": `package repository
import "context"
func (s *Store) FetchIdentityUser(ctx context.Context, id int64) (string, error) { return "", nil }
func (s *Store) ListIdentityUsers(ctx context.Context) ([]string, error) { return nil, nil }
`,
		"internal/repository/identity_user.schema.go": `package repository
import (
	"context"
	"time"
	"github.com/uptrace/bun"
)
type IdentityUserModel struct {
	bun.BaseModel ` + "`" + `bun:"table:users,alias:u"` + "`" + `
	ID int64 ` + "`" + `bun:"id,pk,autoincrement"` + "`" + `
	Username string ` + "`" + `bun:"username,notnull,unique"` + "`" + `
	Email string ` + "`" + `bun:"email,nullzero"` + "`" + `
	CreatedAt time.Time ` + "`" + `bun:"created_at,notnull"` + "`" + `
}
func (*IdentityUserModel) BeforeCreateTable(_ context.Context, query *bun.CreateTableQuery) error {
	query.ForeignKey("(id) REFERENCES accounts (user_id) ON DELETE CASCADE")
	return nil
}
func IdentityUserSchema() {}
`,
	})

	analysis, err := analyzeRoot(filepath.Join(root, "internal"))
	if err != nil {
		t.Fatal(err)
	}
	index := analysis.ArchitectureIndex()

	if index.ModulePath != "example.com/app" {
		t.Fatalf("unexpected module path %q", index.ModulePath)
	}
	assertHandlerIndex(t, index, "identity_user", "identityUserHandler", "RegisterIdentityUsers", []string{"List"})
	assertServiceIndex(t, index, "IdentityUserService", "identity_user", "NewIdentityUserService", []string{"AuthSessionService"}, []string{"Create", "Search"})
	assertStoreIndex(t, index, "identity_user", []string{"FetchIdentityUser", "ListIdentityUsers"})

	users := findTableIndex(index, "users")
	if users == nil {
		t.Fatalf("expected users table, got %#v", index.Tables)
	}
	if users.Model != "IdentityUserModel" || users.Alias != "u" || users.Scope != "identity_user" {
		t.Fatalf("unexpected users table metadata: %#v", users)
	}
	assertFieldIndex(t, *users, "ID", "id", "int64", true, true, false, false, "")
	assertFieldIndex(t, *users, "Username", "username", "string", false, false, true, false, "true")
	assertFieldIndex(t, *users, "Email", "email", "string", false, false, false, true, "")
	if len(users.ForeignKeys) != 1 || users.ForeignKeys[0] != "(id) REFERENCES accounts (user_id) ON DELETE CASCADE" {
		t.Fatalf("unexpected foreign keys: %#v", users.ForeignKeys)
	}
}

func TestIndexTextIncludesSections(t *testing.T) {
	index := indexFixture()

	text := index.Text()
	for _, needle := range []string{
		"tddcheck index: example.com/app",
		"handlers:",
		"- deviceHandler (device) internal/handler/device.handler.go",
		"services:",
		"- DeviceService (device) internal/service/device.service.go",
		"dependencies: AuthSessionService",
		"stores:",
		"- device internal/repository/device.store.go",
		"tables:",
		"- devices (DeviceModel, device) internal/repository/device.schema.go",
		"ID int64 `id` [pk]",
	} {
		if !strings.Contains(text, needle) {
			t.Fatalf("expected text to contain %q, got:\n%s", needle, text)
		}
	}
	if strings.Contains(text, "apis:") {
		t.Fatalf("expected text not to contain API index, got:\n%s", text)
	}
}

func TestAnalysisMarkdownIncludesIndex(t *testing.T) {
	analysis := Analysis{
		Root:       "internal",
		ModulePath: "example.com/app",
		Index:      indexFixture(),
	}

	markdown := analysis.Markdown()
	for _, needle := range []string{
		"# tddcheck Architecture Index",
		"<!-- Code generated by tddcheck; DO NOT EDIT. -->",
		"- Module: `example.com/app`",
		"- Violations: `0`",
		"## Handlers",
		"| `device` | `deviceHandler` | `RegisterDevices` | `internal/handler/device.handler.go` | List    |",
		"## Services",
		"| `DeviceService` | `device` | `internal/service/device.service.go` | `NewDeviceService` | AuthSessionService | List    |",
		"## Stores",
		"| `device` | `internal/repository/device.store.go` | FetchDevice |",
		"## Tables",
		"| `devices` | `DeviceModel` | `device` | `internal/repository/device.schema.go` | `d`   | 1      | 0            |",
		"### `devices`",
		"| `ID`  | `id`   | `int64` | [pk]       |",
	} {
		if !strings.Contains(markdown, needle) {
			t.Fatalf("expected markdown to contain %q, got:\n%s", needle, markdown)
		}
	}
	if strings.Contains(markdown, "## APIs") || strings.Contains(markdown, "No APIs found.") {
		t.Fatalf("expected markdown not to contain API index, got:\n%s", markdown)
	}
}

func TestProjectWriteDocWritesDefaultMarkdownFile(t *testing.T) {
	root := fixture(t, map[string]string{
		"internal/service/device.service.go": `package service
type DeviceService struct{}
func NewDeviceService() *DeviceService { return &DeviceService{} }
func (s *DeviceService) List() {}
`,
		"internal/repository/device.schema.go": `package repository
import "github.com/uptrace/bun"
type DeviceModel struct {
	bun.BaseModel ` + "`" + `bun:"table:devices,alias:d"` + "`" + `
	ID int64 ` + "`" + `bun:"id,pk"` + "`" + `
}
func DeviceSchema() {}
`,
	})
	cwd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		_ = os.Chdir(cwd)
	})
	if err := os.Chdir(root); err != nil {
		t.Fatal(err)
	}

	analysis, err := analyzeRoot("internal")
	if err != nil {
		t.Fatal(err)
	}
	if err := analysis.WriteMarkdown(""); err != nil {
		t.Fatal(err)
	}

	data, err := os.ReadFile(filepath.Join(root, DefaultDocFile))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), "### `devices`") {
		t.Fatalf("expected generated doc to contain devices table, got:\n%s", string(data))
	}
}

func TestProjectAnalyzeIndexesMultipleHandlerRegisters(t *testing.T) {
	root := fixture(t, map[string]string{
		"internal/handler/device.handler.go": `package handler
type deviceHandler struct{}
func RegisterDevices() { deviceHandler{}.registerAdmin() }
func RegisterPublicDevices() { deviceHandler{}.registerPublic() }
func (h deviceHandler) registerAdmin() {}
func (h deviceHandler) registerPublic() {}
`,
	})

	analysis, err := analyzeRoot(filepath.Join(root, "internal"))
	if err != nil {
		t.Fatal(err)
	}
	assertHandlerIndex(t, analysis.ArchitectureIndex(), "device", "deviceHandler", "RegisterDevices", []string{"registerAdmin", "registerPublic"})
	assertHandlerIndex(t, analysis.ArchitectureIndex(), "device", "deviceHandler", "RegisterPublicDevices", []string{"registerAdmin", "registerPublic"})
}

func TestProjectAnalyzeAssignsForeignKeysToReceiverModel(t *testing.T) {
	root := fixture(t, map[string]string{
		"internal/repository/device.schema.go": `package repository
import (
	"context"
	"github.com/uptrace/bun"
)
type DeviceModel struct {
	bun.BaseModel ` + "`" + `bun:"table:devices"` + "`" + `
	ID int64 ` + "`" + `bun:"id,pk"` + "`" + `
}
func (*DeviceModel) BeforeCreateTable(_ context.Context, query *bun.CreateTableQuery) error {
	query.ForeignKey("(room_id) REFERENCES rooms (id)")
	return nil
}
type DevicePortModel struct {
	bun.BaseModel ` + "`" + `bun:"table:device_ports"` + "`" + `
	ID int64 ` + "`" + `bun:"id,pk"` + "`" + `
}
func (*DevicePortModel) BeforeCreateTable(_ context.Context, query *bun.CreateTableQuery) error {
	query.ForeignKey("(device_id) REFERENCES devices (id)")
	return nil
}
type DeviceRowModel struct {
	DeviceModel ` + "`" + `bun:",extend"` + "`" + `
	RoomName string ` + "`" + `bun:"room_name"` + "`" + `
}
`,
	})

	analysis, err := analyzeRoot(filepath.Join(root, "internal"))
	if err != nil {
		t.Fatal(err)
	}
	index := analysis.ArchitectureIndex()
	devices := findTableIndex(index, "devices")
	if devices == nil || len(devices.ForeignKeys) != 1 || devices.ForeignKeys[0] != "(room_id) REFERENCES rooms (id)" {
		t.Fatalf("unexpected devices table: %#v", devices)
	}
	ports := findTableIndex(index, "device_ports")
	if ports == nil || len(ports.ForeignKeys) != 1 || ports.ForeignKeys[0] != "(device_id) REFERENCES devices (id)" {
		t.Fatalf("unexpected ports table: %#v", ports)
	}
	if len(index.Projections) != 1 || index.Projections[0].Model != "DeviceRowModel" || index.Projections[0].Extends[0] != "DeviceModel" {
		t.Fatalf("expected DeviceRowModel projection, got %#v", index.Projections)
	}
}

func indexFixture() Index {
	return Index{
		Root:       "internal",
		ModulePath: "example.com/app",
		Handlers: []HandlerIndex{{
			Scope:     "device",
			Type:      "deviceHandler",
			Registers: []string{"RegisterDevices"},
			File:      "internal/handler/device.handler.go",
			Methods:   []MethodIndex{{Name: "List"}},
		}},
		Services: []ServiceIndex{{
			Scope:        "device",
			Type:         "DeviceService",
			Constructor:  "NewDeviceService",
			File:         "internal/service/device.service.go",
			Methods:      []MethodIndex{{Name: "List"}},
			Dependencies: []string{"AuthSessionService"},
		}},
		Stores: []StoreIndex{{
			Scope:   "device",
			File:    "internal/repository/device.store.go",
			Methods: []MethodIndex{{Name: "FetchDevice"}},
		}},
		Tables: []TableIndex{{
			Scope: "device",
			Model: "DeviceModel",
			Table: "devices",
			Alias: "d",
			File:  "internal/repository/device.schema.go",
			Fields: []FieldIndex{{
				Name:       "ID",
				Column:     "id",
				GoType:     "int64",
				PrimaryKey: true,
			}},
		}},
	}
}

func assertHandlerIndex(t *testing.T, index Index, scope string, handlerType string, register string, methods []string) {
	t.Helper()

	for _, handler := range index.Handlers {
		if handler.Scope != scope {
			continue
		}
		if handler.Type != handlerType || !stringIn(register, handler.Registers) {
			t.Fatalf("unexpected handler metadata for %s: %#v", scope, handler)
		}
		assertMethods(t, handler.Methods, methods)
		return
	}
	t.Fatalf("expected handler %s, got %#v", scope, index.Handlers)
}

func assertServiceIndex(t *testing.T, index Index, serviceType string, scope string, constructor string, dependencies []string, methods []string) {
	t.Helper()

	for _, service := range index.Services {
		if service.Type != serviceType {
			continue
		}
		if service.Scope != scope || service.Constructor != constructor {
			t.Fatalf("unexpected service metadata for %s: %#v", serviceType, service)
		}
		for _, dependency := range dependencies {
			if !stringIn(dependency, service.Dependencies) {
				t.Fatalf("expected dependency %s in %#v", dependency, service.Dependencies)
			}
		}
		assertMethods(t, service.Methods, methods)
		return
	}
	t.Fatalf("expected service %s, got %#v", serviceType, index.Services)
}

func assertStoreIndex(t *testing.T, index Index, scope string, methods []string) {
	t.Helper()

	for _, store := range index.Stores {
		if store.Scope != scope {
			continue
		}
		assertMethods(t, store.Methods, methods)
		return
	}
	t.Fatalf("expected store %s, got %#v", scope, index.Stores)
}

func assertMethods(t *testing.T, values []MethodIndex, methods []string) {
	t.Helper()

	for _, method := range methods {
		found := false
		for _, item := range values {
			if item.Name == method {
				found = true
				break
			}
		}
		if !found {
			t.Fatalf("expected method %s, got %#v", method, values)
		}
	}
}

func findTableIndex(index Index, table string) *TableIndex {
	for itemIndex := range index.Tables {
		if index.Tables[itemIndex].Table == table {
			return &index.Tables[itemIndex]
		}
	}
	return nil
}

func TestScopeFromFilenamePreservesArchitectureNamespace(t *testing.T) {
	tests := map[string]string{
		"device_group.handler.go": "device_group",
		"x.shared.handler.go":     "x.shared",
	}
	for base, want := range tests {
		if got := scopeFromFilename(base); got != want {
			t.Errorf("scopeFromFilename(%q) = %q, want %q", base, got, want)
		}
	}
}

func assertFieldIndex(t *testing.T, table TableIndex, name string, column string, goType string, primaryKey bool, autoIncrement bool, notNull bool, nullable bool, unique string) {
	t.Helper()

	for _, field := range table.Fields {
		if field.Name != name {
			continue
		}
		if field.Column != column ||
			field.GoType != goType ||
			field.PrimaryKey != primaryKey ||
			field.AutoIncrement != autoIncrement ||
			field.NotNull != notNull ||
			field.Nullable != nullable ||
			field.Unique != unique {
			t.Fatalf("unexpected field metadata for %s.%s: %#v", table.Table, name, field)
		}
		return
	}
	t.Fatalf("expected field %s in table %s, got %#v", name, table.Table, table.Fields)
}

func stringIn(value string, values []string) bool {
	for _, item := range values {
		if item == value {
			return true
		}
	}
	return false
}
