package tddcheck

import (
	"fmt"
	"strings"

	"github.com/lwmacct/260622-go-pkg-tddcheck/pkg/markdowntable"
)

func (a Analysis) Markdown() string {
	return a.ProjectIndex().Markdown(a)
}

func (i Index) Markdown(analysis Analysis) string {
	var builder strings.Builder
	builder.WriteString("# tddcheck Architecture Index\n\n")
	builder.WriteString("<!-- Code generated by tddcheck; DO NOT EDIT. -->\n\n")
	_, _ = fmt.Fprintf(&builder, "- Module: `%s`\n", markdownValue(i.ModulePath))
	_, _ = fmt.Fprintf(&builder, "- Root: `%s`\n", markdownValue(i.Root))
	_, _ = fmt.Fprintf(&builder, "- Violations: `%d`\n", len(analysis.Violations))

	builder.WriteString("\n## APIs\n\n")
	if len(i.APIs) == 0 {
		builder.WriteString("No APIs found.\n")
	} else {
		rows := make([][]string, 0, len(i.APIs))
		for _, api := range i.APIs {
			rows = append(rows, []string{
				codeCell(api.Method),
				codeCell(api.FullPath),
				codeCell(api.MountPath),
				codeCell(api.OperationPath),
				codeCell(api.OperationID),
				strings.Join(api.Tags, ", "),
				codeCell(api.Handler),
				codeCell(api.Register),
				codeCell(api.File),
			})
		}
		builder.WriteString(markdowntable.Render(markdowntable.Table{
			Header: []string{"Method", "Full Path", "Mount", "Operation Path", "Operation", "Tags", "Handler", "Register", "File"},
			Rows:   rows,
		}))
	}

	builder.WriteString("\n## Handlers\n\n")
	if len(i.Handlers) == 0 {
		builder.WriteString("No handlers found.\n")
	} else {
		rows := make([][]string, 0, len(i.Handlers))
		for _, handler := range i.Handlers {
			rows = append(rows, []string{
				codeCell(handler.Scope),
				codeCell(handler.Type),
				codeCell(strings.Join(handler.Registers, ", ")),
				codeCell(handler.File),
				methodNames(handler.Methods),
			})
		}
		builder.WriteString(markdowntable.Render(markdowntable.Table{
			Header: []string{"Scope", "Handler", "Register", "File", "Methods"},
			Rows:   rows,
		}))
	}

	builder.WriteString("\n## Services\n\n")
	if len(i.Services) == 0 {
		builder.WriteString("No services found.\n")
	} else {
		rows := make([][]string, 0, len(i.Services))
		for _, service := range i.Services {
			rows = append(rows, []string{
				codeCell(service.Type),
				codeCell(service.Scope),
				codeCell(service.File),
				codeCell(service.Constructor),
				strings.Join(service.Dependencies, ", "),
				methodNames(service.Methods),
			})
		}
		builder.WriteString(markdowntable.Render(markdowntable.Table{
			Header: []string{"Service", "Scope", "File", "Constructor", "Dependencies", "Methods"},
			Rows:   rows,
		}))
	}

	builder.WriteString("\n## Stores\n\n")
	if len(i.Stores) == 0 {
		builder.WriteString("No stores found.\n")
	} else {
		rows := make([][]string, 0, len(i.Stores))
		for _, store := range i.Stores {
			rows = append(rows, []string{
				codeCell(store.Scope),
				codeCell(store.File),
				methodNames(store.Methods),
			})
		}
		builder.WriteString(markdowntable.Render(markdowntable.Table{
			Header: []string{"Scope", "File", "Methods"},
			Rows:   rows,
		}))
	}

	builder.WriteString("\n## Tables\n\n")
	if len(i.Tables) == 0 {
		builder.WriteString("No tables found.\n")
	} else {
		builder.WriteString(markdowntable.Render(markdowntable.Table{
			Header: []string{"Table", "Model", "Scope", "File", "Alias", "Fields", "Foreign Keys"},
			Rows:   tableSummaryRows(i.Tables),
		}))
		builder.WriteString("\n")
		for _, table := range i.Tables {
			name := table.Table
			if name == "" {
				name = "(unknown)"
			}
			_, _ = fmt.Fprintf(&builder, "### `%s`\n\n", name)
			_, _ = fmt.Fprintf(&builder, "- Model: `%s`\n", markdownValue(table.Model))
			_, _ = fmt.Fprintf(&builder, "- Scope: `%s`\n", markdownValue(table.Scope))
			_, _ = fmt.Fprintf(&builder, "- File: `%s`\n", markdownValue(table.File))
			if table.Alias != "" {
				_, _ = fmt.Fprintf(&builder, "- Alias: `%s`\n", markdownValue(table.Alias))
			}

			if len(table.Fields) > 0 {
				builder.WriteByte('\n')
				rows := make([][]string, 0, len(table.Fields))
				for _, field := range table.Fields {
					rows = append(rows, []string{
						codeCell(field.Name),
						codeCell(field.Column),
						codeCell(field.GoType),
						fieldOptions(field),
					})
				}
				builder.WriteString(markdowntable.Render(markdowntable.Table{
					Header: []string{"Field", "Column", "Go Type", "Attributes"},
					Rows:   rows,
				}))
			}

			if len(table.ForeignKeys) > 0 {
				builder.WriteString("\nForeign keys:\n\n")
				for _, foreignKey := range table.ForeignKeys {
					_, _ = fmt.Fprintf(&builder, "- `%s`\n", markdownValue(foreignKey))
				}
			}
			builder.WriteString("\n")
		}
	}

	builder.WriteString("\n## Projections\n\n")
	if len(i.Projections) == 0 {
		builder.WriteString("No projections found.\n")
	} else {
		builder.WriteString(markdowntable.Render(markdowntable.Table{
			Header: []string{"Model", "Scope", "File", "Extends", "Fields"},
			Rows:   projectionSummaryRows(i.Projections),
		}))
		builder.WriteString("\n")
		for _, projection := range i.Projections {
			_, _ = fmt.Fprintf(&builder, "### `%s`\n\n", markdownValue(projection.Model))
			_, _ = fmt.Fprintf(&builder, "- Scope: `%s`\n", markdownValue(projection.Scope))
			_, _ = fmt.Fprintf(&builder, "- File: `%s`\n", markdownValue(projection.File))
			if len(projection.Extends) > 0 {
				_, _ = fmt.Fprintf(&builder, "- Extends: `%s`\n", markdownValue(strings.Join(projection.Extends, ", ")))
			}
			if len(projection.Fields) > 0 {
				builder.WriteByte('\n')
				rows := make([][]string, 0, len(projection.Fields))
				for _, field := range projection.Fields {
					rows = append(rows, []string{
						codeCell(field.Name),
						codeCell(field.Column),
						codeCell(field.GoType),
						fieldOptions(field),
					})
				}
				builder.WriteString(markdowntable.Render(markdowntable.Table{
					Header: []string{"Field", "Column", "Go Type", "Attributes"},
					Rows:   rows,
				}))
			}
			builder.WriteString("\n")
		}
	}

	return strings.TrimRight(builder.String(), "\n") + "\n"
}

func tableSummaryRows(tables []TableIndex) [][]string {
	rows := make([][]string, 0, len(tables))
	for _, table := range tables {
		name := table.Table
		if name == "" {
			name = "(unknown)"
		}
		rows = append(rows, []string{
			codeCell(name),
			codeCell(table.Model),
			codeCell(table.Scope),
			codeCell(table.File),
			codeCell(table.Alias),
			fmt.Sprint(len(table.Fields)),
			fmt.Sprint(len(table.ForeignKeys)),
		})
	}
	return rows
}

func projectionSummaryRows(projections []ProjectionIndex) [][]string {
	rows := make([][]string, 0, len(projections))
	for _, projection := range projections {
		rows = append(rows, []string{
			codeCell(projection.Model),
			codeCell(projection.Scope),
			codeCell(projection.File),
			strings.Join(projection.Extends, ", "),
			fmt.Sprint(len(projection.Fields)),
		})
	}
	return rows
}

func methodNames(methods []MethodIndex) string {
	if len(methods) == 0 {
		return ""
	}
	names := make([]string, 0, len(methods))
	for _, method := range methods {
		names = append(names, method.Name)
	}
	return strings.Join(names, ", ")
}

func markdownValue(value string) string {
	if value == "" {
		return "-"
	}
	return strings.ReplaceAll(value, "`", "\\`")
}

func codeCell(value string) string {
	return "`" + markdownValue(value) + "`"
}
